# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcams', '0002_auto_20170710_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='resort_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
